#!/usr/bin/env python3
"""
embed-data.py — Writes live SharePoint data to a SEPARATE JS file.

Data is written to data/live-data.js as `var LIVE_* = ...` declarations.
index.html loads it via <script src="data/live-data.js"></script> placed
BEFORE the module scripts. Regular script tags block and execute in order,
so the LIVE_* globals exist before any module runs — no async timing issues,
no module changes needed.

This keeps the bid/project data OUT of index.html (lighter page, cacheable
data file, data not embedded in main page source). Cloudflare serves the
.js file correctly as a static asset (verified — only non-existent paths
get SPA fallback).

Usage:
    python3 platform/sync/embed-data.py

Reads from: platform/data/*.json
Writes to:  platform/data/live-data.js
"""

import json
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
PLATFORM_DIR = SCRIPT_DIR.parent
DATA_DIR = PLATFORM_DIR / "data"
OUT_FILE = DATA_DIR / "live-data.js"


def load_json(filename):
    path = DATA_DIR / filename
    if not path.exists():
        print(f"  WARNING: {filename} not found, using empty data")
        return {}
    with open(path) as f:
        return json.load(f)


def main():
    print("embed-data.py — Writing live data to separate JS file")
    print(f"  Data dir: {DATA_DIR}")
    print(f"  Output:   {OUT_FILE}")

    bid_log = load_json("bid-log.json")
    project_master = load_json("project-master.json")
    estimate_template = load_json("estimate-template.json")
    bd_master = load_json("bd-master.json")
    sync_meta = load_json("sync-meta.json")

    blob = {
        "LIVE_BIDS": bid_log.get("bids", []),
        "LIVE_STONE_COSTS": bid_log.get("stone_costs", []),
        "LIVE_FY_GOALS": bid_log.get("fy_goals", {}),
        "LIVE_PROJECTS": project_master.get("projects", []),
        "LIVE_COST_CODES": project_master.get("cost_codes", []),
        "LIVE_KPIS": project_master.get("kpis", {}),
        "LIVE_ESTIMATE": estimate_template.get("line_items", []),
        "LIVE_OH_ITEMS": estimate_template.get("oh_items", []),
        "LIVE_BD": bd_master.get("contacts", []),
        "LIVE_BD_SHEETS": bd_master.get("sheet_names", []),
        "LIVE_SYNC_META": sync_meta,
    }

    lines = ["// Live SharePoint data — generated by embed-data.py. Do not edit by hand."]
    for var, value in blob.items():
        lines.append(f"var {var} = {json.dumps(value, separators=(',', ':'))};")
    # Also expose on window for any module that checks window.LIVE_*
    for var in blob:
        lines.append(f"window.{var} = {var};")

    OUT_FILE.write_text("\n".join(lines) + "\n")

    size_kb = OUT_FILE.stat().st_size / 1024
    print(f"  Bids: {len(blob['LIVE_BIDS'])}")
    print(f"  Projects: {len(blob['LIVE_PROJECTS'])}")
    print(f"  BD contacts: {len(blob['LIVE_BD'])}")
    print(f"  Wrote {size_kb:.0f} KB to data/live-data.js")
    print("  Done.")


if __name__ == "__main__":
    main()
