#!/usr/bin/env node
// Seed the PF Platform `users` table with the known roster + RANDOM temp
// passwords (must_reset=1). Uses Node's WebCrypto (crypto.subtle) with the
// EXACT same PBKDF2 parameters as functions/lib/auth.js so the hashes verify at
// runtime.
//
// Output:
//   - platform/migrations/0002_seed_users.sql   (INSERT statements; NO plaintext)
//   - prints the generated temp passwords to STDOUT (give to Brad, then delete)
//
// SECURITY: temp passwords are printed to the terminal ONCE and are NOT written
// to any committed file. The SQL contains only salted PBKDF2 hashes.
//
// Run:  node platform/migrations/seed-users.mjs
// Then apply 0002_seed_users.sql to D1 the same way as 0001.

import { webcrypto as crypto } from 'node:crypto';
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));

// ---- MUST MATCH functions/lib/auth.js -------------------------------------
const PBKDF2_ITERATIONS = 100000; // match runtime cap (Cloudflare Workers max)
const PBKDF2_HASH = 'SHA-256';
const PBKDF2_KEYLEN_BYTES = 32;
const SALT_BYTES = 16;

function b64urlEncode(bytes) {
  let bin = '';
  for (const b of bytes) bin += String.fromCharCode(b);
  return Buffer.from(bin, 'binary').toString('base64')
    .replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');
}

async function pbkdf2(password, saltBytes, iterations) {
  const keyMaterial = await crypto.subtle.importKey(
    'raw', new TextEncoder().encode(password), { name: 'PBKDF2' }, false, ['deriveBits']);
  const bits = await crypto.subtle.deriveBits(
    { name: 'PBKDF2', salt: saltBytes, iterations, hash: PBKDF2_HASH },
    keyMaterial, PBKDF2_KEYLEN_BYTES * 8);
  return b64urlEncode(new Uint8Array(bits));
}

async function hashPassword(password) {
  const saltBytes = crypto.getRandomValues(new Uint8Array(SALT_BYTES));
  const salt = b64urlEncode(saltBytes);
  const hash = await pbkdf2(password, saltBytes, PBKDF2_ITERATIONS);
  return { salt, hash, iterations: PBKDF2_ITERATIONS };
}

// Human-friendly but strong temp password: 4 groups of 4 base32-ish chars.
function tempPassword() {
  const alphabet = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789'; // no ambiguous 0/O/1/I/L
  const bytes = crypto.getRandomValues(new Uint8Array(16));
  let s = '';
  for (let i = 0; i < 16; i++) {
    s += alphabet[bytes[i] % alphabet.length];
    if (i % 4 === 3 && i !== 15) s += '-';
  }
  return s; // e.g. ABCD-EFGH-JKLM-NPQR (~80 bits)
}

function uuid() { return crypto.randomUUID(); }

function sqlStr(v) { return "'" + String(v).replace(/'/g, "''") + "'"; }

// ---- Roster (Brad's list) -------------------------------------------------
const ROSTER = [
  { name: 'Brad Reinking',    email: 'breinking@pierfoundations.com', role: 'admin' },
  { name: 'Jonathan Reinking',email: 'jreinking@pierfoundations.com', role: 'partner' },
  { name: 'Derek Franke',     email: 'dfranke@pierfoundations.com',   role: 'partner' },
  { name: 'John Willis',      email: 'jwillis@pierfoundations.com',   role: 'field_ops' },
  { name: 'Seth Willis',      email: 'swillis@pierfoundations.com',   role: 'field_ops' },
  { name: 'Jordan Lemay',     email: 'jlemay@pierfoundations.com',    role: 'field_ops' },
];

const now = new Date().toISOString();
const lines = [
  '-- PF Platform — D1 seed users (migration 0002)',
  '-- Generated by seed-users.mjs. Contains ONLY salted PBKDF2 hashes (no plaintext).',
  '-- Temp passwords were printed to the operator terminal at generation time.',
  '-- Apply: npx wrangler@3 d1 execute pf-platform-db --remote --file=platform/migrations/0002_seed_users.sql',
  '-- Idempotent-ish: INSERT OR IGNORE keeps existing rows (re-run will NOT overwrite).',
  '',
];

const creds = [];

for (const u of ROSTER) {
  const pw = tempPassword();
  const { salt, hash, iterations } = await hashPassword(pw);
  const id = uuid();
  const email = u.email.toLowerCase();
  lines.push(
    'INSERT OR IGNORE INTO users ' +
    '(id, name, email, password_hash, salt, iterations, role, active, must_reset, created_at) VALUES (' +
    [sqlStr(id), sqlStr(u.name), sqlStr(email), sqlStr(hash), sqlStr(salt),
     iterations, sqlStr(u.role), 1, 1, sqlStr(now)].join(', ') + ');'
  );
  creds.push({ name: u.name, email, role: u.role, password: pw });
}

const outPath = join(__dirname, '0002_seed_users.sql');
writeFileSync(outPath, lines.join('\n') + '\n', 'utf8');

// ---- Report (STDOUT only — give to Brad, do NOT commit) -------------------
console.log('\nWrote seed SQL (hashes only, no plaintext): ' + outPath + '\n');
console.log('TEMP PASSWORDS (give to Brad to distribute; users must reset on first login):');
console.log('--------------------------------------------------------------------------');
for (const c of creds) {
  console.log(
    c.role.padEnd(10) + '  ' + c.name.padEnd(20) + '  ' + c.email.padEnd(36) + '  ' + c.password
  );
}
console.log('--------------------------------------------------------------------------');
console.log('These passwords are NOT stored anywhere else. Copy them now.\n');
